### ISSUE TITLE
Layer/vl_nnconvt works incorrectly when using the 'size' parameter

### ISSUE THREAD

**Issue by dogatekin** [vlfeat/autonn#10]
The help page of vl_nnconvt writes:

> F is a SINGLE array of dimension FW x FH x K x FD where (FH,FW)
    are the filter height and width, K the number of filters in the
    bank, and FD the depth of a filter (the same as the depth of
    image X). Filter k is givenby elements F(:,:,k,:); this differ
    from VL_NNCONV() where a filter is given by elements
    F(:,:,:,k). FD must be the same as the input depth D.

Therefore, when trying to create a convolution transpose layer to go from a layer with (for example) 1024 feature channels to 512 channels by supplying the 'size' parameter, you would do:

`deconv1 = vl_nnconvt(relu10, 'size', [2, 2, 512, 1024]);`

However, while this creates a filter bank of the correct size, it ends up creating the bias array with a size of 1024x1. This naturally causes the following error:

> Error using vl_nnconvt
The number of elements of BIASES is not the same as the dimenison of the filters.

This is presumably caused by the discrepancy between the order of parameters of the methods vl_nnconv and vl_nnconvt (which is emphasized in the help page of vl_nnconvt), looking at the way Layer/vl_nnconvt is written:

```
% simply create a conv layer first, then switch the function handle

layer = vl_nnconv(varargin{:}) ;
layer.func = @vl_nnconvt ;
```

**Comment by jotaf98** [comment]
Good catch, thanks for reporting! I just committed a fix, and updated the unit tests.
