### ISSUE TITLE
plotPDF function example

### ISSUE THREAD

**Issue by Arminkhodaei** [vlfeat/autonn#19]
Hello;

Could you please give me an example of using `plotPDF`?
More clearly, what's the `obj` argument?
I've got the following error with passing a compiled `Net` to the plotPDF function:

> No appropriate method, property, or field 'plotPDF' for class 'Net'.

Thanks.

**Comment by dbarnes** [comment]
plotPDF operates on Layers not Nets.

This is from memory but for example if you wanted to use plotPDF on the first output of your Net (which I think is usually the objective loss if I remember right) you could do the following.

```
Layer.fromCompiledNet(net){1}.plotPDF;

**Comment by Arminkhodaei** [comment]
Thanks @danbarnes333. I got the point.
