### ISSUE TITLE
Dead Link : Math Functions

### ISSUE THREAD

**Issue by sm176357** [vlfeat/autonn#21]
A minor issue but there is a dead link on the tutorial page under Math Functions :
" The full list of overloads can be seen with methods('Layer'), or **[here](https://github.com/vlfeat/autonn/blob/master/doc/matlab/@Layer/methods.txt)**. "

**Comment by jotaf98** [comment]
Thanks for noticing it, it's fixed now!

I also updated the list, there are many new methods since the last refresh:
https://github.com/vlfeat/autonn/blob/master/doc/methods.txt
