### ISSUE TITLE
Copy weights

### ISSUE THREAD

**Issue by wajahat57** [vlfeat/autonn#33]
Hi 
What is the easiest way to copy weights between two AutoNN networks?
Best Regards

**Comment by ryanwebster90** [comment]
To obtain a cell array of all network parameters for a network, use the "getValue" method of the Net class, e.g.
```Matlab
net1_params = net1.getValue([net1.params.var]);
```
Then, to set network parameters, use the "setValue" method in Net. So, for example, if net1 and net2 had identical topology, you could copy the parameters like so,
```Matlab
net2.setValue([net2.params.var],net1_params);
```

If you want to actually copy a network, see the "deepCopy" method of the Layer class.
