### ISSUE TITLE
Does it lost the function 'vl_argparse'?

### ISSUE THREAD

**Issue by MeredithChai** [vlfeat/autonn#47]
When I clone this prj and try to test an Input() function, at Line 37 in 'matlab\Input.m', it calls the subfunction named 'vl_argparse' and it figures out that the function is undefined. The similar function 'vl_argparsepos' (and the other parts) also has such a problem! So i guess maybe u forget pushing it sometime? :)

**Comment by jotaf98** [comment]
Hi, those functions should be a part of MatConvNet, although they're relatively recent. Can you check which version you have, and whether it's the latest?

**Comment by MeredithChai** [comment]
Thx, problems are solved.
