### ISSUE TITLE
Way to use a network object in parallel

### ISSUE THREAD

**Issue by damdaepark** [vlfeat/autonn#51]
Hi,

I'm curious about if there is a way to utilize a _Net_ object in parallel.

I tried `parfor` and `parfeval` with `parallel.pool.Constant` but it seems does not work.

If you have tried it before and have some example code, please let me know.

I would really appreciate that.

Best regards,

**Comment by jotaf98** [comment]
Hi, if you want to use Net objects in parallel with parfor and they're in CPU mode, it works already.

As for multi-GPU training, that takes synchronization between them so needs a bit more.

This functionality exists in MatConvNet, it just hasn't been interfaced with AutoNN yet. But the blocks are all there if you want to access them.

The main source for this is [cnn_train.m](https://github.com/vlfeat/matconvnet/blob/master/examples/cnn_train.m), which implements multi-GPU training (and a lot of other redundant stuff that you can skip).

Essentially a ParameterServer object holds all the parameters for a network and the workers (inside a parfor or spmd block) use it to grab the latest parameters and communicate back the updates.

Look for the lines that start with "if numGpus" and the use of the ParameterServer in the accumulateGradients function (in the source file I linked).

**Comment by damdaepark** [comment]
As you mentioned, I found parallel implementation is already doable in CPU mode even without using `parallel.pool.Constant`.

Thanks!
