### ISSUE TITLE
Error running minimal examples

### ISSUE THREAD

**Issue by kaganozturk** [vlfeat/autonn#7]
Edit: I updated MatConvNet from https://github.com/vlfeat/matconvnet now it works.

I get error running minimal_lstm and minimal network.

>> minimal_lstm
Index exceeds matrix dimensions.

Error in vl_argparse (line 94)
  value = args{ai+1} ;

Error in vl_nnloss (line 134)
opts = vl_argparse(opts, varargin, 'nonrecursive') ;

Error in Net/eval (line 86)
    [out{:}] = layer.func(args{:}) ;

Error in minimal_lstm (line 73)
  net.eval({'x', data_x, 'y', data_y}) ;

////////////////////////////

>> minimal_network
Index exceeds matrix dimensions.

Error in vl_argparse (line 94)
  value = args{ai+1} ;

Error in vl_nnloss (line 134)
opts = vl_argparse(opts, varargin, 'nonrecursive') ;

Error in Net/eval (line 86)
    [out{:}] = layer.func(args{:}) ;

Error in minimal_network (line 42)
  net.eval({'x', data_x(:,:,:,idx), 'y', data_y(idx)}) ;

I am using MatConvNet version 24, win 64, Matlab 2016a

Thank you so much for your help in advance.

**Comment by jotaf98** [comment]
I tried the same setup and can't reproduce it (with Matlab 2015b instead). This would happen if you're using an older version of MatConvNet (check your path :) ). Anyway glad you got it sorted!
